In [1]:
import pandas as pd
import numpy as np


In [2]:
dfx=pd.read_csv('./Logistic_X_Train.csv')
dfy=pd.read_csv('./Logistic_Y_Train.csv')

In [3]:
X=dfx.values
Y=dfy.values

In [4]:
print(X.shape)
print(X)
k=np.ones((X.shape[0],1))
print(k)
np.hstack((k,X))

(3000, 3)
[[-1.23937466  0.74910149 -0.52851491]
 [-1.03607028  0.80143631 -1.28371152]
 [-0.61557914  1.57952053 -1.39192706]
 ...
 [ 0.08827657  1.63878904 -2.19364056]
 [ 1.52515501  0.85923429  1.50530791]
 [-0.97981744  0.56395376 -1.53939416]]
[[1.]
 [1.]
 [1.]
 ...
 [1.]
 [1.]
 [1.]]


array([[ 1.        , -1.23937466,  0.74910149, -0.52851491],
       [ 1.        , -1.03607028,  0.80143631, -1.28371152],
       [ 1.        , -0.61557914,  1.57952053, -1.39192706],
       ...,
       [ 1.        ,  0.08827657,  1.63878904, -2.19364056],
       [ 1.        ,  1.52515501,  0.85923429,  1.50530791],
       [ 1.        , -0.97981744,  0.56395376, -1.53939416]])

In [5]:
Y.shape

(3000, 1)

In [6]:
print(Y)

[[1]
 [1]
 [1]
 ...
 [1]
 [0]
 [1]]


In [13]:
def hypothesis(x,theta):
    k=np.dot(x,theta)
    return sigmoid(k)
def sigmoid(z):
    return 1.0/(1.0+np.exp(-z))
    

In [14]:
def error(Y,X,theta):
    m = X.shape[0]
    total_error = 0.0
    
    for i in range(m):
        y_hat = hypothesis(X[i],theta)
        total_error += (Y[i]*np.log2(y_hat)+(1-Y[i])*np.log2(1-y_hat)) 
        
    return total_error/m


In [15]:
def get_grad(Y,X,theta):
    
    grad = np.zeros(theta.shape)
    m = X.shape[0]
    for i in range(m):
        y_hat = hypothesis(X[i],theta)
        x = X[i].reshape((-1,1))
        grad += (Y[i] - y_hat)*x
        
        
    return grad/m

In [16]:
def grad_descent(X,Y,learning_rate=0.5):
    theta = np.zeros((X.shape[1],1))
    
    error_list = []
    m=X.shape[0]
    for i in range(500):
        theta = theta + learning_rate*get_grad(Y,X,theta)
        e = error(Y,X,theta)
        error_list.append(e)
        
    return theta,error_list

In [17]:
theta,error_list=grad_descent(X,Y)

In [18]:
print(theta)

[[-1.78203643]
 [ 1.19204401]
 [-3.58655303]]


In [19]:
print(error_list)

[array([-0.69622705]), array([-0.54813651]), array([-0.461998]), array([-0.40577399]), array([-0.36623752]), array([-0.33694666]), array([-0.31438961]), array([-0.29649042]), array([-0.28194439]), array([-0.26989099]), array([-0.25974011]), array([-0.25107375]), array([-0.24358767]), array([-0.23705525]), array([-0.23130427]), array([-0.22620152]), array([-0.22164238]), array([-0.21754355]), array([-0.21383789]), array([-0.21047071]), array([-0.20739697]), array([-0.2045793]), array([-0.2019864]), array([-0.19959186]), array([-0.19737326]), array([-0.19531144]), array([-0.19338991]), array([-0.19159443]), array([-0.18991262]), array([-0.18833367]), array([-0.18684811]), array([-0.18544759]), array([-0.18412474]), array([-0.182873]), array([-0.18168657]), array([-0.18056022]), array([-0.17948931]), array([-0.17846964]), array([-0.17749744]), array([-0.17656929]), array([-0.17568212]), array([-0.17483311]), array([-0.17401973]), array([-0.17323963]), array([-0.1724907]), array([-0.171770

ModuleNotFoundError: No module named 'sklearn.linear_Model'

NameError: name 'LogisticRegression' is not defined